export const categories = [
  {
    id: "writing-content",
    name: "Writing & Content",
    description: "AI tools for content creation, copywriting, and text generation",
    icon: "✍️",
    count: 245,
    subcategories: ["Blog Writing", "Copywriting", "Technical Writing", "Social Media Content"],
  },
  {
    id: "design-creative",
    name: "Design & Creative",
    description: "Creative AI tools for design, art, and visual content",
    icon: "🎨",
    count: 189,
    subcategories: ["Logo Design", "UI/UX Design", "Image Generation", "Graphic Design"],
  },
  {
    id: "code-development",
    name: "Code & Development",
    description: "AI-powered development tools and coding assistants",
    icon: "💻",
    count: 156,
    subcategories: ["Code Generation", "Debugging", "Documentation", "Testing"],
  },
  {
    id: "marketing-seo",
    name: "Marketing & SEO",
    description: "AI tools for digital marketing and search optimization",
    icon: "📈",
    count: 134,
    subcategories: ["Social Media", "Email Marketing", "SEO Optimization", "Analytics"],
  },
  {
    id: "image-generation",
    name: "Image Generation",
    description: "AI-powered image creation and editing tools",
    icon: "🖼️",
    count: 98,
    subcategories: ["Art Generation", "Photo Editing", "Avatar Creation", "Background Removal"],
  },
  {
    id: "chatbots-automation",
    name: "Chatbots & Automation",
    description: "Conversational AI and workflow automation tools",
    icon: "🤖",
    count: 87,
    subcategories: ["Customer Support", "Lead Generation", "Workflow Automation", "Virtual Assistants"],
  },
  {
    id: "video-audio",
    name: "Video & Audio",
    description: "AI tools for video editing, audio processing, and multimedia creation",
    icon: "🎥",
    count: 76,
    subcategories: ["Video Editing", "Audio Generation", "Podcast Creation", "Music Production"],
  },
  {
    id: "data-analytics",
    name: "Data & Analytics",
    description: "AI-powered data analysis, visualization, and business intelligence tools",
    icon: "📊",
    count: 92,
    subcategories: ["Data Visualization", "Predictive Analytics", "Business Intelligence", "Statistical Analysis"],
  },
  {
    id: "education-learning",
    name: "Education & Learning",
    description: "AI tools for personalized learning, tutoring, and educational content",
    icon: "📚",
    count: 68,
    subcategories: ["Language Learning", "Tutoring", "Content Creation", "Assessment"],
  },
  {
    id: "healthcare-medical",
    name: "Healthcare & Medical",
    description: "AI tools for medical diagnosis, health monitoring, and healthcare management",
    icon: "🏥",
    count: 54,
    subcategories: ["Medical Imaging", "Diagnosis", "Health Monitoring", "Drug Discovery"],
  },
  {
    id: "finance-accounting",
    name: "Finance & Accounting",
    description: "AI tools for financial analysis, accounting automation, and investment insights",
    icon: "💰",
    count: 73,
    subcategories: ["Financial Planning", "Accounting", "Investment Analysis", "Risk Management"],
  },
  {
    id: "ecommerce-retail",
    name: "E-commerce & Retail",
    description: "AI tools for online retail, inventory management, and customer experience",
    icon: "🛒",
    count: 61,
    subcategories: ["Product Recommendations", "Inventory Management", "Customer Service", "Pricing Optimization"],
  },
  {
    id: "legal-compliance",
    name: "Legal & Compliance",
    description: "AI tools for legal research, document analysis, and compliance management",
    icon: "⚖️",
    count: 42,
    subcategories: ["Legal Research", "Document Review", "Compliance", "Contract Analysis"],
  },
  {
    id: "research-development",
    name: "Research & Development",
    description: "AI tools for scientific research, experimentation, and innovation",
    icon: "🔬",
    count: 58,
    subcategories: ["Scientific Research", "Laboratory Automation", "Data Collection", "Innovation Management"],
  },
  {
    id: "human-resources",
    name: "Human Resources",
    description: "AI tools for recruitment, employee management, and HR operations",
    icon: "👥",
    count: 49,
    subcategories: ["Recruitment", "Performance Management", "Employee Engagement", "HR Analytics"],
  },
  {
    id: "sales-crm",
    name: "Sales & CRM",
    description: "AI tools for sales automation, customer relationship management, and lead generation",
    icon: "📞",
    count: 67,
    subcategories: ["Lead Generation", "Sales Automation", "Customer Management", "Pipeline Analytics"],
  },
  {
    id: "project-management",
    name: "Project Management",
    description: "AI tools for project planning, team collaboration, and workflow optimization",
    icon: "📋",
    count: 55,
    subcategories: ["Task Management", "Team Collaboration", "Resource Planning", "Progress Tracking"],
  },
]

export const aiStacks = [
  {
    id: "solopreneur",
    name: "Solopreneur",
    description: "Essential AI tools for solo entrepreneurs to scale their business efficiently",
    icon: "👤",
    color: "blue",
    tools: [
      { name: "10Web", category: "Marketing", type: "Tool", rating: 4.8 },
      { name: "Ada", category: "Customer Service", type: "Agent", rating: 4.7 },
      { name: "AdCreative", category: "Advertising", type: "Tool", rating: 4.6 },
      { name: "Adobe Express", category: "Graphic Design", type: "Tool", rating: 4.9 },
    ],
  },
  {
    id: "early-startups",
    name: "Early Startups",
    description: "Collaborative AI tools perfect for growing teams and lean operations",
    icon: "🌱",
    color: "green",
    tools: [
      { name: "Adobe Firefly", category: "Image & Video Content", type: "Tool", rating: 4.8 },
      { name: "AI Magicx", category: "AI Brand Visibility", type: "Agent", rating: 4.5 },
      { name: "AirOps", category: "Multi-use AI Tools", type: "Tool", rating: 4.7 },
      { name: "Albert.ai", category: "Digital Advertising", type: "Agent", rating: 4.6 },
    ],
  },
  {
    id: "business-productivity",
    name: "Business Productivity",
    description: "Professional-grade AI tools for streamlined workflows and efficiency",
    icon: "💼",
    color: "purple",
    tools: [
      { name: "Algolia", category: "Search & Discovery", type: "Tool", rating: 4.8 },
      { name: "Abilene", category: "Finance", type: "Tool", rating: 4.4 },
      { name: "Altrays", category: "Analytics", type: "Tool", rating: 4.7 },
      { name: "Amazon Q Developer", category: "Coding", type: "Agent", rating: 4.8 },
    ],
  },
  {
    id: "content-creators",
    name: "Content Creators",
    description: "Creative AI tools for video, audio, and visual content production",
    icon: "🎬",
    color: "pink",
    tools: [
      { name: "Arcads", category: "Video Generation", type: "Tool", rating: 4.5 },
      { name: "ArtFlow", category: "Generative Art", type: "Tool", rating: 4.6 },
      { name: "Asana", category: "Project Management", type: "Tool", rating: 4.8 },
      { name: "Alexa", category: "Voice AI", type: "Agent", rating: 4.3 },
    ],
  },
  {
    id: "indie-hackers",
    name: "Indie Hackers",
    description: "Lean AI tools for independent developers and makers building products",
    icon: "⚡",
    color: "yellow",
    tools: [
      { name: "Auto-GPT", category: "No-Code", type: "Agent", rating: 4.7 },
      { name: "AutoDraw", category: "Design", type: "Tool", rating: 4.4 },
      { name: "BARD AI", category: "AI Music Generation", type: "Tool", rating: 4.6 },
      { name: "Beatoven", category: "AI Music Generation", type: "Tool", rating: 4.8 },
    ],
  },
  {
    id: "vibe-coders-builders",
    name: "Vibe Coders & Builders",
    description: "Stylish AI tools for creative developers who value aesthetics and innovation",
    icon: "🎯",
    color: "indigo",
    tools: [
      { name: "10Web", category: "Marketing", type: "Tool", rating: 4.8 },
      { name: "Ada", category: "Customer Service", type: "Agent", rating: 4.7 },
      { name: "AdCreative", category: "Advertising", type: "Tool", rating: 4.6 },
      { name: "Adobe Express", category: "Graphic Design", type: "Tool", rating: 4.9 },
    ],
  },
]

export const tools = [
  {
    id: 1,
    name: "Advanced content writing and blog post generator",
    description:
      "Transform your content creation process with our advanced AI writing tool. Generate high-quality blog posts, articles, and marketing copy in minutes, not hours. Our AI understands context, maintains your brand voice, and creates SEO-optimized content that engages your audience.",
    category: "Writing & Content",
    subcategory: "Blog Writing",
    rating: 4.9,
    reviews: 1247,
    badge: "Top Rated",
    type: "Tool",
    provider: "ContentAI Labs",
    pricing: {
      model: "subscription",
      startingPrice: "$5/month",
      plans: [
        { name: "Starter", price: "$5/month", features: ["10 articles/month", "Basic templates", "Email support"] },
        {
          name: "Pro",
          price: "$15/month",
          features: ["50 articles/month", "Advanced templates", "Priority support", "SEO optimization"],
        },
        {
          name: "Enterprise",
          price: "$49/month",
          features: ["Unlimited articles", "Custom templates", "Dedicated support", "API access"],
        },
      ],
    },
    features: ["AI Writing", "SEO Optimization", "Brand Voice", "Multiple Languages"],
    website: "https://contentai-labs.com",
    demoVideo: "https://youtube.com/watch?v=demo1",
    images: ["/ai-writing-tool-interface.png"],
    tags: ["writing", "content", "blog", "seo", "marketing"],
    targetAudience: "Content creators, marketers, bloggers",
    apiAvailable: true,
    languages: ["English", "Spanish", "French", "German"],
    integrations: ["WordPress", "Shopify", "HubSpot", "Slack"],
  },
  {
    id: 2,
    name: "Professional logo and brand identity creator",
    description:
      "Create stunning professional logos and complete brand identities with AI-powered design tools. Perfect for startups, small businesses, and entrepreneurs looking to establish a strong visual presence.",
    category: "Design & Creative",
    subcategory: "Logo Design",
    rating: 4.8,
    reviews: 892,
    badge: "Level 2",
    type: "Tool",
    provider: "BrandAI Studio",
    pricing: {
      model: "one-time",
      startingPrice: "$29",
      plans: [
        { name: "Basic", price: "$29", features: ["5 logo concepts", "PNG/JPG files", "Basic customization"] },
        {
          name: "Professional",
          price: "$79",
          features: ["15 logo concepts", "Vector files", "Brand guidelines", "Social media kit"],
        },
        {
          name: "Enterprise",
          price: "$199",
          features: ["Unlimited concepts", "Full brand package", "Commercial license", "Priority support"],
        },
      ],
    },
    features: ["Logo Generation", "Brand Guidelines", "Vector Files", "Commercial License"],
    website: "https://brandai-studio.com",
    demoVideo: "https://youtube.com/watch?v=demo2",
    images: ["/logo-design-ai-interface.png"],
    tags: ["logo", "branding", "design", "identity", "startup"],
    targetAudience: "Entrepreneurs, small businesses, designers",
    apiAvailable: false,
    languages: ["English"],
    integrations: ["Figma", "Adobe Creative Suite", "Canva"],
  },
  {
    id: 3,
    name: "Code Generator Pro",
    description:
      "Advanced AI-powered code generation tool that helps developers write clean, efficient code faster. Supports multiple programming languages and frameworks with intelligent suggestions and automated documentation.",
    category: "Code & Development",
    subcategory: "Code Generation",
    rating: 4.9,
    reviews: 1534,
    badge: "Pro",
    type: "Tool",
    provider: "DevAI Solutions",
    pricing: {
      model: "subscription",
      startingPrice: "$19/month",
      plans: [
        {
          name: "Individual",
          price: "$19/month",
          features: ["Basic code generation", "5 languages", "Community support"],
        },
        {
          name: "Team",
          price: "$49/month",
          features: ["Advanced features", "15+ languages", "Team collaboration", "Priority support"],
        },
        {
          name: "Enterprise",
          price: "$99/month",
          features: ["Custom models", "Unlimited usage", "On-premise deployment", "Dedicated support"],
        },
      ],
    },
    features: ["Multi-language Support", "Code Completion", "Documentation Generation", "Debugging Assistant"],
    website: "https://devai-solutions.com",
    demoVideo: "https://youtube.com/watch?v=demo3",
    images: ["/code-generation-ai-interface.png"],
    tags: ["coding", "development", "programming", "automation", "productivity"],
    targetAudience: "Developers, software engineers, tech teams",
    apiAvailable: true,
    languages: ["English", "Chinese", "Japanese"],
    integrations: ["VS Code", "GitHub", "GitLab", "Jira", "Slack"],
  },
]

export const popularSearches = ["Content Writing", "Image Generation", "Code Assistant", "Chatbots"]

export const stats = {
  totalTools: "20+",
  happyUsers: "16K+",
  categories: "17+",
  averageRating: "4.6/5",
}
